# Font configuration
font-family = JetBrains Mono
font-style = regular
font-style-bold = bold
font-style-italic = italic
font-style-bold-italic = bold-italic
font-size = 10
font-feature =
font-synthetic-style = bold,italic,bold-italic

# Theme
theme = AlienBlood
#theme = Brogrammer
#theme = Laser

# Build
gtk-adwaita = true
gtk-custom-css = true
gtk-wide-tabs = true

# Clipboard
clipboard-read = allow
clipboard-write = allow
clipboard-trim-trailing-spaces = true
clipboard-paste-protection = true

# Text rendering
text-blending = native
grapheme-width-method = unicode

# Window appearance
window-width = 0
window-height = 0
window-padding-x = 12
window-padding-y = 12
window-decoration = true
background-opacity = 0.90

# Mouse behavior
mouse-hide-while-typing = true
mouse-scroll-multiplier = 1.5

# Terminal features
shell-integration-features = no-cursor,sudo
desktop-notifications = true
bold-is-bright = true
term = xterm-256color

# Cursor
cursor-style = bar
cursor-text = 000000
cursor-color = 50fa7b

# Etc
abnormal-command-exit-runtime = 250
scrollback-limit = 10000000
link-url = true
maximize = false
fullscreen = false
title =
class =
x11-instance-name =
working-directory =

# Shader configuration
# Uncomment only ONE shader at a time!

# Galaxy (not my work)
custom-shader = ~/.config/ghostty/shaders/solar.glsl

# Original Trippy
#custom-shader = ~/.config/ghostty/shaders/trippy.glsl

# Matrix Digital Rain
#custom-shader = ~/.config/ghostty/shaders/matrix_rain.glsl

# Glitch CRT
#custom-shader = ~/.config/ghostty/shaders/glitch_crt.glsl

# Liquid Neon
#custom-shader = ~/.config/ghostty/shaders/liquid_neon.glsl

# Kaleidoscope
#custom-shader = ~/.config/ghostty/shaders/kaleidoscope.glsl

# Vaporwave
#custom-shader = ~/.config/ghostty/shaders/vaporwave.glsl

# Plasma Wave
#custom-shader = ~/.config/ghostty/shaders/plasma_wave.glsl

# Quantum Field
#custom-shader = ~/.config/ghostty/shaders/quantum_field.glsl

# Cyberpunk City
#custom-shader = ~/.config/ghostty/shaders/cyberpunk_city.glsl

# Fractal Tunnel
#custom-shader = ~/.config/ghostty/shaders/fractal_tunnel.glsl

# Keep animation enabled for all shaders
#custom-shader-animation = true