# Font configuration
font-family = JetBrains Mono
font-style = regular
font-style-bold = bold
font-style-italic = italic
font-style-bold-italic = bold-italic
font-size = 10
font-feature = 
font-synthetic-style = bold,italic,bold-italic

# Theme
theme = Brogrammer

# Text rendering
text-blending = native
grapheme-width-method = unicode

# Window appearance
window-width = 0
window-height = 0
window-padding-x = 12
window-padding-y = 12
window-decoration = true
background-opacity = 0.90

# Mouse behavior
mouse-hide-while-typing = true
mouse-scroll-multiplier = 1.5

# Terminal features
shell-integration-features = no-cursor,sudo
clipboard-paste-protection = true
desktop-notifications = true
bold-is-bright = true
term = xterm-256color

# Cursor
cursor-style = bar
cursor-text = 000000
cursor-color = 50fa7b

# Shader configuration
# Uncomment only ONE shader at a time!

# Original Trippy
#custom-shader = ~/.config/ghostty/shaders/trippy.glsl

# Matrix Digital Rain
#custom-shader = ~/.config/ghostty/shaders/matrix_rain.glsl

# Glitch CRT
#custom-shader = ~/.config/ghostty/shaders/glitch_crt.glsl

# Liquid Neon
#custom-shader = ~/.config/ghostty/shaders/liquid_neon.glsl

# Kaleidoscope
#custom-shader = ~/.config/ghostty/shaders/kaleidoscope.glsl

# Vaporwave
#custom-shader = ~/.config/ghostty/shaders/vaporwave.glsl

# Plasma Wave
#custom-shader = ~/.config/ghostty/shaders/plasma_wave.glsl

# Quantum Field
#custom-shader = ~/.config/ghostty/shaders/quantum_field.glsl

# Cyberpunk City
#custom-shader = ~/.config/ghostty/shaders/cyberpunk_city.glsl

# Fractal Tunnel
#custom-shader = ~/.config/ghostty/shaders/fractal_tunnel.glsl

# Keep animation enabled for all shaders
#custom-shader-animation = true
